# Generated by Django 4.2.27 on 2026-02-17 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'vehicle_types',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=32)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_spots', to='api.vehicletype')),
            ],
            options={
                'db_table': 'parking_spots',
            },
        ),
        migrations.CreateModel(
            name='PaidParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paid_parking', to='api.parkingspot')),
            ],
            options={
                'db_table': 'paid_parking',
            },
        ),
        migrations.CreateModel(
            name='HandicapSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_permit', models.BooleanField(default=True)),
                ('signed', models.BooleanField(default=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handicap_details', to='api.parkingspot')),
            ],
            options={
                'db_table': 'handicap_spots',
            },
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(fields=('lot_code', 'label'), name='unique_spot_per_lot'),
        ),
    ]
