# Generated by Django 4.2.27 on 2026-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicletype_parkingspot_paidparking_handicapspot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parkingspot',
            name='unique_spot_per_lot',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='section',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='parkingspot',
            constraint=models.UniqueConstraint(fields=('section', 'label'), name='unique_spot_per_section'),
        ),
    ]
