# Generated by Django 4.2.27 on 2026-02-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_parkingspot_unique_spot_per_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
