# Generated by Django 4.2.27 on 2026-02-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
